# -*- coding: utf-8 -*-
"""densenet_ser2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q_TT4H4niBXaUclWHdtjqwUaFcBKA-uv
"""

from fastapi import FastAPI, Request
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
import random
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import torchvision.models as models

# FastAPI 및 템플릿 설정
app = FastAPI()
templates = Jinja2Templates(directory="templates")

# 모델 및 데이터셋 설정
num_classes = 10
classes = ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')
dataset_path = './data/svhn'

transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4377, 0.4438, 0.4728), (0.1980, 0.2010, 0.1970)),
])

testset = torchvision.datasets.SVHN(root=dataset_path, split='test', download=True, transform=transform_test)

model = models.densenet121(pretrained=True)
model.features[0] = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
num_features = model.classifier.in_features
model.classifier = nn.Linear(num_features, num_classes)

model_path = 'densenet121_svhn_final_model_epochs_10.pth'
model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu')))
model.eval()

# 랜덤 예측 이미지 시각화 함수
def visualize_random_predictions():
    idx = random.randint(0, len(testset) - 1)
    img, label = testset[idx]
    img = img.unsqueeze(0).to("cpu")  # Add batch dimension
    torchvision.utils.save_image(img, "./imgs/f.jpg")

    with torch.no_grad():
        output = model(img)
        _, predicted = torch.max(output.data, 1)

    return predicted.item(), label

@app.get("/test")
async def read_root(request: Request):
    predicted, label = visualize_random_predictions()
    result = f'Predicted: {classes[predicted]} | True: {classes[label]}'
    context = {"result": result}
    return templates.TemplateResponse("index2.html", {"request": request, "context": context})

app.mount("/imgs", StaticFiles(directory="imgs"), name='images')